version: 1.2
workflows:
 - name: gas_identification_wf2
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_gas_identification.wdl
   testParameterFiles:
    - /files/empty.json
 - name: ani-test
   subclass: WDL
   primaryDescriptorPath: /tasks/task_mummer-ani.wdl
   testParameterFiles:
    - /files/empty.json
